#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# __Author__ = 'gaogao'

# from selenium import webdriver
#
# browser = webdriver.Chrome()
# browser.get('http://www.baidu.com')

# chrome所在路径
from selenium import webdriver

browser = webdriver.Chrome('C:\Program Files (x86)\chromedriver_win32\chromedriver.exe')
browser.get('http://www.baidu.com/')